version: '3'

services:

  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
        - STACK_VERSION=${STACK_VERSION:-latest}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    user: opensearch